(DEFINE COMMENT . (QUOTE MICROSHAFT-QUERIES-LISP))
(DEFINE COMMENT . (QUOTE LOAD-SPO-FUNCTIONS-LISP-AND-MICROSHAFT-DB-LISP-FIRST))

(DEFINE COMMENT . (QUOTE ===PART-6-QUERIES===))

(DEFINE COMMENT . (QUOTE EACH-QUERY-CALLS-ANSWER-WITH-THREE-ARGUMENTS))
(DEFINE COMMENT . (QUOTE 1-THE-QUERY-EXPRESSION-QUOTED))
(DEFINE COMMENT . (QUOTE 2-THE-OUTPUT-TEMPLATE-QUOTED))
(DEFINE COMMENT . (QUOTE 3-THE-DATABASE-AS-MICROSHAFT-DB-A-ZERO-ARG-LAMBDA-CALL))
(DEFINE COMMENT . (QUOTE VARIABLES-IN-PATTERNS-ARE-WRITTEN-AS-TWO-ELEMENT-LISTS))
(DEFINE COMMENT . (QUOTE WHOSE-CAR-IS-THE-ATOM-QUESTION-MARK-EG-?-P-OR-?-J))

(DEFINE COMMENT . (QUOTE Q1-WHO-ARE-THE-COMPUTER-PROGRAMMERS))
(ANSWER
  (QUOTE (TRIPLE (? P) JOB (COMPUTER PROGRAMMER)))
  (QUOTE (? P))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q2-ALL-JOBS))
(ANSWER
  (QUOTE (TRIPLE (? P) JOB (? J)))
  (QUOTE ((? P) HAS-JOB (? J)))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q3-BENS-DIRECT-REPORTS))
(ANSWER
  (QUOTE (TRIPLE (? P) SUPERVISOR BITDIDDLE-BEN))
  (QUOTE (? P))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q4-JOIN-BENS-REPORTS-WITH-THEIR-JOBS))
(DEFINE COMMENT . (QUOTE THE-VARIABLE-?-P-APPEARS-IN-BOTH-TRIPLES-LINKING-THEM))
(ANSWER
  (QUOTE (AND (TRIPLE (? P) SUPERVISOR BITDIDDLE-BEN)
              (TRIPLE (? P) JOB (? J))))
  (QUOTE ((? P) HAS-JOB (? J)))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q5-TWO-HOP-CHAIN-WHO-IS-TWO-LEVELS-BELOW-WARBUCKS))
(DEFINE COMMENT . (QUOTE ?-MID-LINKS-THE-TWO-SUPERVISOR-TRIPLES))
(ANSWER
  (QUOTE (AND (TRIPLE (? P) SUPERVISOR (? MID))
              (TRIPLE (? MID) SUPERVISOR WARBUCKS-OLIVER)))
  (QUOTE ((? P) UNDER (? MID)))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q6-OR-PROGRAMMERS-OR-TECHNICIANS))
(DEFINE COMMENT . (QUOTE EACH-BRANCH-IS-TRIED-RESULTS-ARE-UNIONED))
(ANSWER
  (QUOTE (OR (TRIPLE (? P) JOB (COMPUTER PROGRAMMER))
             (TRIPLE (? P) JOB (COMPUTER TECHNICIAN))))
  (QUOTE (? P))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q7-NOT-HAVE-SUPERVISOR-BUT-NOT-BENS-DIRECT-REPORT))
(DEFINE COMMENT . (QUOTE NOT-SUCCEEDS-ONLY-WHEN-THE-INNER-QUERY-FINDS-NOTHING))
(ANSWER
  (QUOTE (AND (TRIPLE (? P) SUPERVISOR (? B))
              (NOT (TRIPLE (? P) SUPERVISOR BITDIDDLE-BEN))))
  (QUOTE ((? P) BOSS IS (? B)))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q8-SLUMERVILLE-NESTED-LIST-PATTERN-MATCHING-WITH-REST))
(DEFINE COMMENT . (QUOTE THE-DOT-IN-SLUMERVILLE-DOT-?-REST-IS-CDR-NOTATION))
(DEFINE COMMENT . (QUOTE IT-MATCHES-ANY-ADDRESS-LIST-STARTING-WITH-SLUMERVILLE))
(ANSWER
  (QUOTE (TRIPLE (? P) ADDRESS (SLUMERVILLE . (? REST))))
  (QUOTE ((? P) LIVES-IN SLUMERVILLE))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q9-WHAT-CAN-A-COMPUTER-WIZARD-DO-LIST-AS-SUBJECT))
(DEFINE COMMENT . (QUOTE THE-SUBJECT-COMPUTER-WIZARD-IS-A-LIST-NOT-AN-ATOM))
(DEFINE COMMENT . (QUOTE MATCH-HANDLES-THIS-UNIFORMLY-VIA-THE-CONS-CASE))
(ANSWER
  (QUOTE (TRIPLE (COMPUTER WIZARD) CAN-DO-JOB (? J)))
  (QUOTE (WIZARD-CAN-COVER (? J)))
  (MICROSHAFT-DB))

(DEFINE COMMENT . (QUOTE Q10-THREE-TRIPLE-JOIN-DISPLAY-NAMES-IN-REPORTING-CHAIN))
(DEFINE COMMENT . (QUOTE THREE-VARIABLES-LINK-THREE-TRIPLES-INTO-ONE-RESULT))
(DEFINE COMMENT . (QUOTE NAME-TRIPLES-CARRY-THE-SICP-STYLE-DISPLAY-NAME-LISTS))
(ANSWER
  (QUOTE (AND (TRIPLE (? P) SUPERVISOR (? BOSS))
              (TRIPLE (? BOSS) NAME (? BNAME))
              (TRIPLE (? P) NAME (? PNAME))))
  (QUOTE ((? PNAME) REPORTS-TO (? BNAME)))
  (MICROSHAFT-DB))
